version: 0.2

phases:
  install:
    commands:
      - dotnet restore
      - cd WindyUI.Documentation/TailwindBuild
      - npm install
      - npm run buildcss
      - cd ../..
  build:
    commands:
      - dotnet publish -o publish
        
artifacts:
  files: 
    - 'publish/wwwroot/*'
