version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet publish -o publish
        
artifacts:
  files: 
    - 'publish/**/*'
